name: Build TaskFlow APK

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generate Native Folders (Trick for Termux Users)
        run: flutter create .

       - name: Install Dependencies
        run: flutter pub get

      - name: Generate App Icon
        run: dart run flutter_launcher_icons # Eksekusi perubah ikon sebelum di-build

      - name: Build Release APK
        run: flutter build apk --release --split-per-abi # Biar APK-nya kecil

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
        name: TaskFlow-Release-APK
          # Path-nya sedikit berubah kalau pakai split-per-abi
        path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
